default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ali
  password: alidb
  host: localhost

development:
  <<: *default
  database: teacher_portal_development

test:
  <<: *default
  database: teacher_portal_test

production:
  <<: *default
  database: teacher_portal_production